# Generated by Django 2.0.13 on 2019-08-19 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190816_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8444252-365d-4e79-8b37-f5d072a6b91d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
